apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tempo
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: tempo
      version: ">=1.0.0 <2.0.0"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: monitoring
      interval: 12h
  values:
    tempo:
      repository: grafana/tempo
      tag: latest
      
      storage:
        trace:
          backend: local
          local:
            path: /var/tempo/traces
      
      receivers:
        jaeger:
          protocols:
            thrift_http:
              endpoint: 0.0.0.0:14268
            grpc:
              endpoint: 0.0.0.0:14250
        otlp:
          protocols:
            http:
              endpoint: 0.0.0.0:4318
            grpc:
              endpoint: 0.0.0.0:4317
        zipkin:
          endpoint: 0.0.0.0:9411
    
    persistence:
      enabled: true
      size: "<override-with-kustomize>"
    
    service:
      type: ClusterIP
