apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tempo
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: tempo
      version: "^1.24.0"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: monitoring
      interval: 12h
  values:
    tempo:
      server:
        http_listen_port: 3200

      ingester:
        flush_check_period: 10s
        trace_idle_period: 10s
        max_block_duration: 30m
        complete_block_timeout: 1h

      querier:
        max_concurrent_queries: 20

      queryFrontend:
        search:
          concurrent_jobs: 2000

      retention: 24h

      storage:
        trace:
          backend: local
          local:
            path: /var/tempo/traces
          wal:
            path: /var/tempo/wal
      
      receivers:
        jaeger:
          protocols:
            thrift_http:
              endpoint: 0.0.0.0:14268
            grpc:
              endpoint: 0.0.0.0:14250
        otlp:
          protocols:
            grpc:
              endpoint: 0.0.0.0:4317
            http:
              endpoint: 0.0.0.0:4318

    tempoQuery:
      enabled: true
      service:
        port: 16686
    
    serviceMonitor:
      enabled: true
    persistence:
      enabled: true
      size: "<override-with-kustomize>"
    
    service:
      type: ClusterIP
