apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: argocd
  namespace: argocd
spec:
  interval: 30m
  chart:
    spec:
      chart: argo-cd
      version: "5.x.x"  # specify your desired version
      sourceRef:
        kind: HelmRepository
        name: argocd
        namespace: argocd
      interval: 12h
