apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: argocd
  namespace: argocd
spec:
  interval: 30m
  chart:
    spec:
      chart: argo-cd
#     apply the latest release
#     version: "9.x.x"
      sourceRef:
        kind: HelmRepository
        name: argocd
        namespace: argocd
      interval: 12h
