kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: staging

networking:
  podSubnet: "10.246.0.0/16"
  serviceSubnet: "10.98.0.0/12"
  disableDefaultCNI: false
  ipFamily: ipv4

nodes:
  - role: control-plane
    image: kindest/node:v1.34.0
    extraPortMappings:
      # Expose kube-apiserver on localhost
      - containerPort: 6443
        hostPort: 7443
        listenAddress: "127.0.0.1"
        protocol: TCP

      # NodePort testing for ingress (80 / 443)
      - containerPort: 30080
        hostPort: 9080
        protocol: TCP
      - containerPort: 30443
        hostPort: 9443
        protocol: TCP

    # Add SANs to kubeadm for TLS certificates
    kubeadmConfigPatches:
      - |
        apiVersion: kubeadm.k8s.io/v1beta3
        kind: ClusterConfiguration
        apiServer:
          certSANs:
            - "127.0.0.1"
            - "localhost"
            - "k8s-staging.local"

  - role: worker
    image: kindest/node:v1.34.0
