apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tetragon
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/staging/tetragon
  prune: true
  wait: true
  timeout: 10m
  retryInterval: 2m
  healthChecks:
    - apiVersion: apps/v1
      kind: DaemonSet
      name: tetragon
      namespace: kube-system
  