apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rook-ceph-cluster
  namespace: rook-ceph
spec:
  values:
    cephClusterSpec:
      dashboard:
        enabled: true
        ssl: true

    network:
      connections:
        encryption:
          enabled: true
        compression:
          enabled: true
        requireMsgr2: true