# Cilium MUST be deployed first (it's the CNI!)
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cilium
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/staging/cilium
  prune: false  # NEVER prune CNI accidentally!
  wait: true
  timeout: 15m
  retryInterval: 2m
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: cilium-operator
      namespace: kube-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tetragon
  namespace: flux-system
spec:
  interval: 10m
  dependsOn:
    - name: cilium
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/stagingn/tetragon
  prune: true
  wait: true
  timeout: 10m
  retryInterval: 2m
  healthChecks:
    - apiVersion: apps/v1
      kind: DaemonSet
      name: tetragon
      namespace: kube-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: argocd
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/staging/argocd
  prune: true
  wait: false
  timeout: 5m
  retryInterval: 2m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: chaos-mesh
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/staging/chaos-mesh
  prune: true
  wait: false
  timeout: 5m
  retryInterval: 2m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kube-prometheus-stack
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/staging/kube-prometheus-stack
  prune: true
  wait: true
  timeout: 15m
  retryInterval: 2m
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: kube-prometheus-stack-operator
      namespace: monitoring
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: loki
  namespace: flux-system
spec:
  interval: 10m
  dependsOn:
    - name: kube-prometheus-stack
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/staging/loki
  prune: true
  wait: false
  timeout: 10m
  retryInterval: 2m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tempo
  namespace: flux-system
spec:
  interval: 15m
  dependsOn:
    - name: kube-prometheus-stack
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/staging/tempo
  prune: true
  wait: false
  timeout: 10m
  retryInterval: 2m