---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: crds
<<<<<<< Updated upstream
  namespace: flux-system
spec:
  interval: 12h
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./clusters/staging/infrastructure/crds
  prune: false
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: network
  namespace: flux-system
spec:
  interval: 10m
  dependsOn:
    - name: crds
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./clusters/staging/infrastructure/network
  prune: false
  wait: true
=======
  namespace: flux-system
spec:
  interval: 12h
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./clusters/staging/infrastructure/crds
  prune: false
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: network
  namespace: flux-system
spec:
  interval: 10m
  dependsOn:
    - name: crds
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./clusters/staging/infrastructure/network
  prune: false
  wait: true
>>>>>>> Stashed changes
  timeout: 15m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: observability
  namespace: flux-system
spec:
  interval: 10m
  dependsOn:
    - name: network
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./clusters/staging/infrastructure/observability
  prune: true
  wait: false
  timeout: 15m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: platform
  namespace: flux-system
spec:
  interval: 10m
  dependsOn:
    - name: network
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./clusters/staging/infrastructure/platform
  prune: true
  wait: false
  timeout: 10m