apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 30m
  chart:
    spec:
      chart: cilium
      version: "^1.18.3"  
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: kube-system
      interval: 12h
  install:
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    # Core Cilium configuration
    cluster:
      name: "<override-with-kustomize>"
      id: <override-with-kustomize>  # Unique cluster ID for multi-cluster
    
    # Performance and security
    bpf:
      masquerade: true
      hostLegacyRouting: false

    # Replace kube-proxy with eBPF
    kubeProxyReplacement: true

    # Replace MetalLB
    ## BGP Control Plane 
    bgpControlPlane:
      enabled: false

    ## L2 Announcements
    l2announcements:
      enabled: false
    l2podAnnouncements:
      enabled: false
      interface: "eth0"

    
    # Enable Hubble for observability
    hubble:
      enabled: true
      relay:
        enabled: true
        replicas: 1
      ui:
        enabled: true
        replicas: 1
        ingress:
          enabled: true
          className: cilium  # or nginx/traefik
          hosts: [<override-with-kustomize>]

      metrics:
        enabled:
        - dns:query
        - drop
        - tcp
        - flow
        - icmp
        - http
        dashboards:
          enabled: true
        serviceMonitor:
          enabled: true

    # Enable Gateway API support
    gatewayAPI:
      enabled: true

    # Operator configuration
    operator:
      replicas: 2
      prometheus:
        enabled: true
        serviceMonitor:
          enabled: true

    ipv6:
      enabled: false
    
    # Bandwidth Manager (for better TCP performance)
    bandwidthManager:
      enabled: true
      bbr: true
    
    # Enable local redirect policy
    localRedirectPolicies:
      enabled: true
    
    # Service monitoring
    prometheus:
      enabled: true
      serviceMonitor:
        enabled: true
    
    # Encryption (optional - impacts performance)
    encryption:
      enabled: <override-with-kustomize>
      type: wireguard