# Cilium MUST be deployed first (it's the CNI!)
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cilium
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/production/cilium
  prune: false  # NEVER prune CNI accidentally!
  wait: true
  timeout: 15m
  retryInterval: 2m
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: cilium-operator
      namespace: kube-system
  