apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: chaos-mesh
  namespace: flux-system
spec:
  interval: 10m
  dependsOn:
    - name: cilium
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/production/chaos-mesh
  prune: true
  wait: false
  timeout: 5m
  retryInterval: 2m