apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tetragon
  namespace: kube-system
spec:
  interval: 30m
  chart:
    spec:
      chart: tetragon
      version: "^1.6.0"
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: kube-system
      interval: 12h
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    tetragon:
      enabled: true
      prometheus:
        enabled: true
        serviceMonitor:
          enabled: true
    
    # Export events
    export:
      mode: "stdout"
      stdout:
        enabledCommand: true
        enabledArgs: true
            
#   # Enterprise features (if you have license)
#   tetragonOperator:
#     enabled: true
#     prometheus:
#       enabled: true
#       serviceMonitor:
#         enabled: true