apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  values:

    singleBinary:
      replicas: 1
      persistence:
        enabled: true
        size: 1Gi

    memcached:   
      enabled: true

    memcachedExporter:
      enabled: true

    resultsCache:
      enabled: true
      allocatedMemory: 512
      persistence:
        enabled: false
        storageSize: 1Gi
    chunksCache:
      enabled: true
      allocatedMemory: 1024
      l2:
        persistence:
          enabled: false
          storageSize: 1Gi
