apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  values:
    singleBinary:
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 500m
          memory: 512Mi   

    memcachedChunks:
      enabled: true
      resources:
        requests:
          cpu: 50m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 256Mi
      # Add this to override the memcached memory allocation
      allocatedMemory: 128  # This sets the -m flag in MB

    memcachedFrontend:
      enabled: true
      resources:
        requests:
          cpu: 50m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 256Mi
      # Add this to override the memcached memory allocation
      allocatedMemory: 256  # This sets the -m flag in MB

    memcachedIndexQueries:
      enabled: true
      resources:
        requests:
          cpu: 50m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 256Mi
      # Add this to override the memcached memory allocation
      allocatedMemory: 128  # This sets the -m flag in MB  

    memcachedIndexWrites:
      enabled: true
      resources:
        requests:
          cpu: 50m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 256Mi
      # Add this to override the memcached memory allocation
      allocatedMemory: 128  # This sets the -m flag in MB  