apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: chaos-mesh
  namespace: chaos-mesh
spec:
  interval: 30m
  chart:
    spec:
      chart: chaos-mesh
      version: "^2.8.0"  
      sourceRef:
        kind: HelmRepository
        name: chaos-mesh
        namespace: chaos-mesh
      interval: 12h
  values: {}
