apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: loki
      version: "^6.46.0"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: monitoring
      interval: 12h
  values:
    loki:
      auth_enabled: false
      commonConfig:
        replication_factor: 1
      storage:
        type: filesystem
      limits_config:
        volume_enabled: true
      
      useTestSchema: false
      storage_config:
        boltdb_shipper:
          active_index_directory: /var/loki/index
          cache_location: /var/loki/cache
          shared_store: filesystem
        filesystem:
          directory: /var/loki/chunks

      schemaConfig:
        configs:
          - from: "2024-09-01"
            store: boltdb-shipper
            object_store: filesystem
            schema: v13
            index:
              prefix: index_
              period: 24h
    
    singleBinary:
      replicas: 1
      persistence:
        enabled: true
        size: "<override-with-kustomize>"
    
    memcached:   
      enabled: <override-with-kustomize>

    memcachedExporter:
      enabled: <override-with-kustomize>
      # image:
      #   repository: prom/memcached-exporter
      #   tag: v0.15.3
      #   pullPolicy: IfNotPresent
      # resources:
      #   requests: {}
      #   limits: {}
    resultsCache:
      enabled: <override-with-kustomize>
      allocatedMemory: <override-with-kustomize> # default: 1024
    chunksCache:
      enabled: <override-with-kustomize>
      allocatedMemory: <override-with-kustomize> # default: 8192
      
    # Deploy the Gateway (nginx)
    gateway:
      enabled: true

    
    # Disable components not needed for single binary mode
    read:
      replicas: 0
    write:
      replicas: 0
    backend:
      replicas: 0
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: promtail
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: promtail
      version: "^6.17.1"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: monitoring
      interval: 12h
  values:
    config:
      clients:
        - url: http://loki-gateway.monitoring.svc.cluster.local/loki/api/v1/push
      positions:
        filename: /data/positions.yaml