apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: loki
      version: "^6.46.0"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: monitoring
      interval: 12h
  values:
    # SimpleScalable and Distributed REQUIRE the use of object storage.
    # Cannot be provided with our current setup: We need Openstack Swift
    deploymentMode: SingleBinary
    loki:
      auth_enabled: false
      commonConfig:
        replication_factor: 1
      storage:
        type: filesystem
      limits_config:
        volume_enabled: true
      
      useTestSchema: false
      storage_config:
        boltdb_shipper:
          active_index_directory: /var/loki/index
          cache_location: /var/loki/cache
          shared_store: filesystem
        filesystem:
          directory: /var/loki/chunks

      schemaConfig:
        configs:
          - from: "2024-09-01"
            store: boltdb-shipper
            object_store: filesystem
            schema: v13
            index:
              prefix: index_
              period: 24h

    singleBinary:
      replicas: 1
      persistence:
        enabled: true
        size: 1Gi
      service:
        type: "ClusterIP"
      resources:
        requests:
          cpu: 500m
          memory: 512Mi
        limits:
          cpu: 1000m
          memory: 1Gi

    # Deploy the Gateway (nginx)
    gateway:
      # SingleBinary Loki instance already exposes all HTTP endpoints on the same port (default 3100)
      # The gateway adds unnecessary complexity — it’s only useful when multiple microservices
      # (distributor, querier, etc.) need unified routing.
      enabled: false
    
    read:
      replicas: 0
    write:
      replicas: 0
    backend:
      replicas: 0

    memcached:   
      enabled: false # default: true
    memcachedExporter:
      enabled: false # default: true
    
    resultsCache:
      enabled: false # default: true
      allocatedMemory: <override-with-kustomize> # default: 1024
      persistence:
        enabled: <override-with-kustomize> # default: false
        storageSize: <override-with-kustomize> # default: 10Gi
    chunksCache:
      enabled: false # default: true
      allocatedMemory: <override-with-kustomize> # default: 8192
      l2:
        persistence:
          enabled: <override-with-kustomize> # default: false
          storageSize: <override-with-kustomize> # default: 10Gi
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: promtail
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: promtail
      version: "^6.17.1"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: monitoring
      interval: 12h
  values:
    config:
      enabled: true
      enableTracing: true
      clients:
        - url: http://loki-gateway.monitoring.svc.cluster.local/loki/api/v1/push
      positions:
        filename: /run/promtail/positions.yaml     
    sidecar:
      configReloader:
        enabled: false